server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/tasksdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: tasks
    password: tasks123!
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  h2:
    console:
      enabled: true
      path: /h2-console
  redis:
    host: 172.17.64.175
    port: 6379
    database: 0
  cache:
    type: redis
    redis:
      time-to-live: 600000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.web: debug
    org.springframework.cache: debug
    org.springframework.data.redis: warn

security:
  jwt:
    secret: "1234567890abcdefghijklmnopqrstuvwxyz"
    expiration-seconds: 86400
    issuer: "tasks-app"

springdoc:
  swagger-ui:
    path: /swagger-ui.html