server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:tasksdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  redis:
    host: localhost
    port: 6379
    database: 0
  cache:
    type: redis
    redis:
      time-to-live: 600000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

security:
  jwt:
    secret: "1234567890abcdefghijklmnopqrstuvwxyz"
    expiration-seconds: 86400
    issuer: "tasks-app"